Homework YC
Otus-DevOps-2022-02/dmitriy-re_infra pull request #3
Opened 2022-03-27 14:02 UTC by dmitriy-re

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-03-27 14:29 UTC, dmitriy-re commented
![yc_01](https://user-images.githubusercontent.com/78013137/160286272-32a88bca-5847-4791-910a-4da137e9a4c1.png)
Посмотрел задачи проверки , порт 27017 слушается, только на внутреннем шз

2022-03-27 14:33 UTC, dmitriy-re commented
B сервис  mongodb работает
![yc_02](https://user-images.githubusercontent.com/78013137/160286498-2ad90ca3-d215-4c39-82c2-7605a7ce13b1.png)

2022-03-29 08:25 UTC, mrgreyves requested changes
Здравствуйте!)
Да, с монгой в тестах такие приколы бывают
Но у вас так же еще и проблема с приложением
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/34331259/160567507-b0e3b9e4-cab3-4cc3-8ad4-4fac3f1316bf.png">
Приложение "пятисотит" вместо положенного 200 кода ответа
Нужно пофиксить, кажется что puma может быть запущена не в том каталоге или не хватает файлов приложения
ДЗ возвращаю на доработку

2022-03-29 19:18 UTC, dmitriy-re commented
Переразвернул виртуалку на Ubuntu 16.04, теперь puma работает.

2022-03-30 10:48 UTC, mrgreyves approved these changes
Здравствуйте!)
Вполне возможно в первый раз была проблема с версией puma
ДЗ принимаю =)

2022-03-30 19:10 UTC, merged