Packer_homework
Otus-DevOps-2022-02/dmitriy-re_infra pull request #4
Opened 2022-04-03 18:35 UTC by dmitriy-re

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-03 19:21 UTC, dmitriy-re commented
У меня локально validate проходит
packer validate -var-file=variables.json ubuntu16.json
The configuration is valid.

а ругается если проверять через фейковый json  на неправильный путь к ключу
packer validate -var-file=variables.json.example ubuntu16.json
Error: Failed to prepare build: "yandex"

1 error(s) occurred:

* fail to read service account key file: key file '/home/keystore/key.json' read
fail: open /home/keystore/key.json: no such file or directory

2022-04-04 14:26 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно создать ФЕЙКОВЫЙ ключик доступа к yandex cloud и запушить его в репозиторий
Так же нужно в манифесте пакера указать где находится этот ключик
Приключение на 10 минут, дз нужно подправить =)

2022-04-04 18:17 UTC, dmitriy-re commented
Добавил key.json

2022-04-06 08:17 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув =)

2022-04-06 13:59 UTC, merged