Terraform 2
Otus-DevOps-2022-02/dmitriy-re_infra pull request #6
Opened 2022-04-11 20:29 UTC by dmitriy-re

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-11 20:34 UTC, dmitriy-re commented
Не понял почему нужно удалить файл vpc.tf и как вместо него использовать переменные, если сеть еще не созданна. Получается в одном модуле нужно добавить файл vpc.tf , а в другом мудуле задать сеть через переменную?

2022-04-11 20:39 UTC, dmitriy-re commented
![terraform-2_vpc](https://user-images.githubusercontent.com/78013137/162827892-a8630569-78fa-4827-b180-537ba50a45f4.png)
Это непонятно. Переменные это только те ресурсы, которые уже созданы. А сеть у нас еще не создана.

2022-04-12 08:41 UTC, mrgreyves commented
Все так, кажется что сеть должна создаваться отдельно

2022-04-12 08:42 UTC, mrgreyves requested changes
Здравствуйте!)
Ответил ваше вопрос
Так же у вас не хватает достаточно большого количества файлов
ДЗ возвращаю на доработку

2022-04-13 12:15 UTC, dmitriy-re commented
Доделал задание по terraform-2

2022-04-14 16:32 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Не хватает файла storage-bucket.tf
Его стоит добавить, кажется что вы просто не закомитили его
Правки не должны быть очень большими, дз возвращаю на доработку

2022-04-14 18:18 UTC, dmitriy-re commented
Здравствуйте, у меня действительно нет файла storage-bucket.tf .
Что-то я не вижу в д\з откуда он должен появиться и что в нем должно находиться.
Может это задание со * ?

2022-04-15 06:25 UTC, dmitriy-re commented
Добавил пустой файл storage-bucket.tf . Но в д.з. не нашел упоминайний про этот файл.

2022-04-15 06:29 UTC, dmitriy-re commented
Добрый день!
 
Не нашел в д.з. упоминаний про файл storage-bucket.tf .
Откуда он должен взяться?
Может это задание со * ?
--
Дмитрий Чекрыгин 
>Четверг, 14 апреля 2022, 19:32 +03:00 от Vladimir Drozdetskiy ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>Здравствуйте!)
>Проверил ваше дз
>Не хватает файла storage-bucket.tf
>Его стоит добавить, кажется что вы просто не закомитили его
>Правки не должны быть очень большими, дз возвращаю на доработку
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <Otus-DevOps-2022-02/dmitriy-re_infra/pull/6/review/942527730 @ github . com>
 
 

Отправлено из Почты  Mail.ru
 

2022-04-18 13:28 UTC, mrgreyves approved these changes
Апрув =)

2022-04-18 13:42 UTC, merged