Ansible 3
Otus-DevOps-2022-02/dmitriy-re_infra pull request #9
Opened 2022-04-27 18:50 UTC by dmitriy-re

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-28 08:43 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
С ansible у вас все хорошо
Давайте пофиксим историю с пакером, нужно добавить фейковый ключ доступа
Приключение на пару минут =)

2022-05-06 12:24 UTC, dmitriy-re commented
Так фейковый ключ уже добавлен, это key.json в директории parker, или вы про какой-то другой ключ?

2022-05-06 12:40 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил вам комментарий

2022-05-06 12:40 UTC, mrgreyves commented on .gitignore
>  key.json
Нет ключа то
Он жеж в игноре

2022-05-06 12:44 UTC, dmitriy-re commented on .gitignore
>  key.json
Поправил путь до ключа в фейковом variables.json.example

2022-05-06 12:45 UTC, dmitriy-re commented on .gitignore
>  key.json
Ключ в директории /packer

2022-05-06 12:46 UTC, dmitriy-re commented on .gitignore
>  key.json
На githaub виден в директории packer

2022-05-06 13:19 UTC, mrgreyves requested changes
Снова смотрим в тесты
Там так же проблемы с путями до плейбуков ansible

2022-05-06 13:52 UTC, dmitriy-re commented
Поправил путь

2022-05-10 10:16 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув =)

2022-05-11 15:09 UTC, merged